= Terraform demos: json policy overriding
Anton Stamenov <anton.stamenov@gmail.com>
ifndef::env-github[:icons: font]
ifdef::env-github[]
:idprefix:
:idseparator: -
:source-language: terraform
:language: {source-language}
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:source-highlighter: highlightjs
:aws_iam_policy_document: https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html


Use terraform to override json policies.

It is possible to override json policies in terraform by using {aws_iam_policy_document}[`data "aws_iam_policy_document"`]

To do this, specify `source_json`, which can be either external json file or another {aws_iam_policy_document}[`data "aws_iam_policy_document"`]. This is the policy document that will be overridden.

The overriding part should be specified with `override_json`, where again this can be external json file or {aws_iam_policy_document}[`data "aws_iam_policy_document"`].

The `key` is the `Sid` of the policy statements. If `Sid` matches in the `source_json` and `override_json`, then the one from `override_json` will be used.

NOTE: If `Sid` is empty then it cannot be overridden.



.Example: demo.tf
[source,terraform]
----
data "aws_iam_policy_document" "override" {
  source_json = file("plicies/original_policy.json")
  override_json = file("plicies/overriding_policy.json")
}

output "json_document" {
  value = data.aws_iam_policy_document.override.json
}

----
